# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Application-Plugin-TmplInnerOuter
version:      1.11
version_from: lib/CGI/Application/Plugin/TmplInnerOuter.pm
installdirs:  site
requires:
    CGI::Application:              4
    Data::Dumper:                  2
    Exporter:                      5
    HTML::Template::Default:       1
    LEOCHARRE::DEBUG:              1
    Test::Simple:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
