# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Application-Plugin-TmplInnerOuter
version:      1.07
version_from: lib/CGI/Application/Plugin/TmplInnerOuter.pm
installdirs:  site
requires:
    HTML::Template::Default:       1.02
    LEOCHARRE::DEBUG:              1.02
    Test::Simple:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
